[project]
name = 'Collective-Dream-Exploration-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dream-state]
path = 'contracts/dream-state.clar'
clarity_version = 2
epoch = 2.5

[contracts.subconscious-data]
path = 'contracts/subconscious-data.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
